### ISSUE TITLE
Special functions for sorted arrays

### ISSUE THREAD

**Issue by mfigurski80** [danielpclark/array_tool#20]
As mentioned in the title, would be awesome to see some of these functions (`intersect` cough cough) be able to process pre-sorted arrays faster. I got a significant speedup by avoiding the n^2 runtime with this:
``` rust
pub trait IntersectSorted<T> {
    /// Intersect two sorted sequences
    fn intersect(&mut self, other: &Self);
}

impl<T: PartialEq + PartialOrd> IntersectSorted<T> for Vec<T> {
   fn intersect(&mut self, other: &Self) {
        let (mut i, mut j, mut cursor) = (0, 0, 0);
        while cursor + i < self.len() && j < other.len() {
            if self[cursor + i] == other[j] {
                self[cursor] = self[cursor + i];
                cursor += 1;
                j += 1;
                continue;
            }
            if self[cursor + i] > other[j] {
                j += 1;
            } else {
                i += 1;
            }
        }
        self.resize(cursor, self[0]);
    }
}
```

Potentially out-of-scope, understandable, but some specific functions that cater to sorted sequences would be awesome

EDIT :: updated code to work. Sorry, being lazy with my hw assignment...

**Comment by mfigurski80** [comment]
Just a heads up: I'd love to implement something like this with SortedVec. Think it would be a great thing for this package to include. Just don't want to open a PR that'll be ignored forever. Let me know if you'd be interested in letting me contribute this feature

**Comment by danielpclark** [comment]
Hey @mfigurski80 , you're not ignored, I'm simply not notified unless you tag me.  I'd love for any good refactor on this project.  Thank you so much!

**Comment by danielpclark** [comment]
Hey @mfigurski80 I've approved it and merged it in to the master branch but haven't released a crate of it yet.  I have one question about a comment you left behind:

```rust
if ord(&other[j], &out[i]) {
    // ^ should other[j] be ordered before out[i]?
```
https://github.com/danielpclark/array_tool/blob/master/src/sorted_vec.rs#L163

Have you found the code to work as expected and can this comment be removed?

**Comment by mfigurski80** [comment]
Hey @danielpclark.
Apologies, I realize this looks like a TODO note. This was meant more as an explanation of the condition being tested in the if statement -- I frequently have to look up what direction comparisons like these actually go, so I thought this was an appropriate spot for a comment.

Can be rephrased or deleted at your discretion.
