### ISSUE TITLE
String library functions do not work with UTF8

### ISSUE THREAD

**Issue by VladimirMarkelov** [danielpclark/array_tool#5]
I added a test to test/string.rs:
 assert_eq!("ééé".subst_marks(vec![1], "Z"), "éZé");

and 'cargo test' crashes on:

---- it_substitutes_character_at_each_indexed_point stdout ----
        thread 'it_substitutes_character_at_each_indexed_point' panicked at 'byte index 1
is not a char boundary; it is inside 'é' (bytes 0..2) of `ééé`', C:\bot\slave\stable-dist-
rustc-win-gnu-64\build\src\libcore\str/mod.rs:1771
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by danielpclark** [comment]
I'll take a look at this.  Sorry I didn't see this issue earlier.

**Comment by danielpclark** [comment]
> UTF-8
>
> Strings are always valid UTF-8. This has a few implications, the first of which is that if you need a non-UTF-8 string, consider [OsString](https://doc.rust-lang.org/std/ffi/struct.OsString.html). It is similar, but without the UTF-8 constraint. The second implication is that you cannot index into a String:
>
> let s = "hello";
>
> println!("The first letter of s is {}", s[0]); // ERROR!!!Run
>
> Indexing is intended to be a constant-time operation, but UTF-8 encoding does not allow us to do this. Furthermore, it's not clear what sort of thing the index should return: a byte, a codepoint, or a grapheme cluster. The bytes() and chars() methods return iterators over the first two, respectively.

source: https://doc.rust-lang.org/std/string/struct.String.html

**Comment by VladimirMarkelov** [comment]
From one hand, I agree - built-in functions work in the same way. From the other hand, it is helper library, and that is why I think it should make work with UTF8 strings easier.

Another example:

assert_eq!("é é".justify_line(5), "é   é");
thread 'it_justifies_one_line_in_for_string' panicked at 'assertion failed: `(left
 == right)` (left: `"é é"`, right: `"é   é"`)', tests\string.rs:7

I understand why the assert fails here - because each of é is two bytes length and the function does nothing since the length of original string is 5 bytes. From non-developer point of view the function is incorrect because a person sees only 3 characters, so the function must add 2 extra spaces between é's. If an app requires i18n, the function is not helpful and developers have to implement the same function theirselves.

**Comment by danielpclark** [comment]
I didn't post that as an excuse not to implement this.  More as a note for myself to reference on this issue.

I do think this should be fixed and I'll need to figure a way of doing that.

**Comment by VladimirMarkelov** [comment]
No problem. Not long time ago I had to work with a lot of UTF8 texts(and 'justify' was one of the things I needed), that is why I tested the library with non-ASCII strings. After that I just decided to let you know.

**Comment by danielpclark** [comment]
@VladimirMarkelov Update made.  It now works with Unicode.

**Comment by danielpclark** [comment]
Ooops!  Didn't check justify
